spring:
  profiles:
    active: '@activatedProfile@'

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    path: /

app:
  mode: '@activatedProfile@'

---
spring:
  config:
    activate:
      on-profile: pc
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    hibernate:
    ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: dev